name: RandomFallingBlocks
version: '${project.version}'
main: xyz.joscodes.randomfallingblocks.RandomFallingBlocks
api-version: 1.18
authors: [ Jos ]
description: i'm lazy
website: joscodes.xyz

commands:
  blocks:
    usage: /blocks
    description: RandomBlock's Main Command
permissions:
  blocks.*:
    description: Grants you all permissions for Blocks
    default: op
